linters-settings:
  gci:
    sections:
      - prefix(github.com/KirMaid/avito-shop)

  shadow:
    enabled: true # Включение shadow вместо govet.check-shadowing

  dupl:
    threshold: 100

  errorlint:
    errorf: true

  errcheck:
    check-type-assertions: true
    check-blank: true

  exhaustive:
    check-generated: false
    default-signifies-exhaustive: false

  funlen:
    lines: 65
    statements: 40

  gocognit:
    min-complexity: 15

  gocyclo:
    min-complexity: 10

  goconst:
    min-len: 2
    min-occurrences: 2

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - unnecessaryBlock

  gofumpt:
    extra-rules: true

  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return

  govet:
    check-shadowing: false # Отключено, так как используется shadow

  misspell:
    locale: US

  nestif:
    min-complexity: 4

  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - unused
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - forbidigo
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - err113
    - gofmt
    - gofumpt
    - goimports
    - mnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tparallel
    - thelper
    - typecheck
    - unconvert
    - unparam
    - wsl
    - whitespace

issues:
  exclude-dirs:
    - api
    - docs
  exclude-rules:
    - path: integration-test
      linters:
        - paralleltest
        - godot
    - path: internal/app/handlers/http
      linters:
        - godot